<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\Mail\NewUserWelcomeMail;
use App\Models\post;
use App\Models\profilepage;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Mail;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'username',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];



protected static function boot()
{
    
parent::boot(); //todo: change autogenerated stub

static ::created(function($user){

$user->profilepage()->create([

'title' =>$user->username,

]);


Mail::to($user->email)->send(new NewUserWelcomeMail());


});
}





public function following(){


return $this->belongsToMany(profilepage::class);

}




 

    public function profilepage(){

return $this->hasOne(profilepage::class);


    }



    public function posts(){


return $this->hasMany(post::class)->orderBy('created_at', 'DESC');

    }









}
